#!/usr/bin/env bash
# Setup Atlassian API credentials for jira-helper.sh

set -e

JIRA_CONFIG="${HOME}/.jira"

echo "=== Atlassian API Credentials Setup ==="
echo ""

# Check if .jira already exists
if [ -f "$JIRA_CONFIG" ]; then
  echo "WARNING: ${JIRA_CONFIG} already exists"
  read -p "Overwrite existing credentials? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted. Existing credentials preserved."
    exit 0
  fi
  # Backup existing config
  cp "$JIRA_CONFIG" "${JIRA_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
  echo "Backed up existing config"
fi

echo ""
echo "You'll need three pieces of information:"
echo ""
echo "1. Your Atlassian email address"
echo "   - This is the email you use to log into Jira/Confluence"
echo ""
echo "2. Your Atlassian site URL"
echo "   - Example: yourcompany.atlassian.net (without https://)"
echo ""
echo "3. An Atlassian API token"
echo "   - Create one at: https://id.atlassian.com/manage-profile/security/api-tokens"
echo "   - Click 'Create API token'"
echo "   - Give it a label like 'jira-helper' or 'CLI access'"
echo "   - Copy the token (you'll only see it once!)"
echo ""

read -p "Press Enter to continue..."
echo ""

# Prompt for email
read -p "Enter your Atlassian email: " ATLASSIAN_USER
if [ -z "$ATLASSIAN_USER" ]; then
  echo "ERROR: Email is required"
  exit 1
fi

# Prompt for site URL
echo ""
echo "Enter your Atlassian site URL (without https://)"
echo "Example: yourcompany.atlassian.net"
read -p "Site URL: " ATLASSIAN_SITE_URL
if [ -z "$ATLASSIAN_SITE_URL" ]; then
  echo "ERROR: Site URL is required"
  exit 1
fi
# Strip https:// if user included it
ATLASSIAN_SITE_URL="${ATLASSIAN_SITE_URL#https://}"

# Prompt for API token
echo ""
echo "Enter your Atlassian API token"
echo "(Create at: https://id.atlassian.com/manage-profile/security/api-tokens)"
read -s -p "API Token: " ATLASSIAN_API_TOKEN
echo
if [ -z "$ATLASSIAN_API_TOKEN" ]; then
  echo "ERROR: API token is required"
  exit 1
fi

# Write config file
cat > "$JIRA_CONFIG" << EOF
# Atlassian API Credentials
# Generated by setup-credentials.sh on $(date)

export ATLASSIAN_USER="${ATLASSIAN_USER}"
export ATLASSIAN_SITE_URL="${ATLASSIAN_SITE_URL}"
export ATLASSIAN_API_TOKEN="${ATLASSIAN_API_TOKEN}"
EOF

# Set restrictive permissions
chmod 600 "$JIRA_CONFIG"

echo ""
echo "Credentials saved to: ${JIRA_CONFIG}"
echo "File permissions set to 600 (owner read/write only)"
echo ""

# Test the credentials
echo "Testing API connection..."
if command -v curl >/dev/null 2>&1; then
  response=$(curl -s -u "${ATLASSIAN_USER}:${ATLASSIAN_API_TOKEN}" \
    -H 'Accept: application/json' \
    "https://${ATLASSIAN_SITE_URL}/rest/api/3/myself" 2>/dev/null)

  if echo "$response" | grep -q "emailAddress"; then
    display_name=$(echo "$response" | grep -o '"displayName":"[^"]*"' | cut -d'"' -f4)
    echo ""
    echo "SUCCESS! Connected as: ${display_name}"
    echo ""
    echo "Setup complete. You can now use jira-helper.sh functions:"
    echo "  - eod_report"
    echo "  - jira_metrics_volume"
    echo "  - jira_metrics_personal"
    echo "  - get_jira_issue TICKET-123"
    echo ""
  else
    echo ""
    echo "WARNING: Could not verify credentials"
    echo "Response: $response"
    echo ""
    echo "Please check:"
    echo "1. Email address is correct"
    echo "2. Site URL is correct (without https://)"
    echo "3. API token is valid and not expired"
    echo ""
    echo "You can re-run this script to update credentials"
  fi
else
  echo ""
  echo "curl not found - skipping connection test"
  echo "Credentials saved, but not verified"
fi

echo ""
echo "Security note:"
echo "- Your API token is stored in ${JIRA_CONFIG}"
echo "- This file has restrictive permissions (600)"
echo "- Do NOT commit this file to version control"
echo "- Add ${JIRA_CONFIG} to your .gitignore if needed"
