run-name: JDS flow1 ${{ github.GITHUB_RUN_ATTEMPT }}

on:
  push:

  workflow_dispatch:
    inputs:
      vs1:
             type: string
             description: "String 1"
             required: false
      vs2:
             type: string
             description: "String 2"
             required: false
      vs3:
             type: string
             description: "String 3"
             required: false
      vs4:
             type: string
             description: "String 4"
             required: false
      vs5:
             type: string
             description: "String _XX_"
             required: false
      vs6:
             type: string
             description: "String 6"
             required: false
      vn1:
             type: number
             description: "String 1"
             default: 3
             required: true
      vn2:
             type: number
             description: "String 2"
             required: false
      vn3:
             type: number
             description: "String 3"
             required: false
      vn4:
             type: number
             description: "String 4"
             required: false

jobs:
  env:
  platform: azure
  region: us

  dumpenv-1:
    runs-on: ubuntu-latest
  
    steps:
    - name: "env sort"
      run: |
        env | sort
        echo "# env: ${{ inputs.vn1 }}"

  dumpenv-2:
    runs-on: ubuntu-latest
    steps:
    - name: "other env"
      run: |
        env | sort
        echo "# env.plat: ${{ env.platform }}"
  
